#!/bin/bash
FDISK_PATH=/sbin/fdisk
#Comma seporated list of devices. Ex:
#DEVICES_TO_SKIP='/dev/sda /dev/sdb'
DEVICES_TO_SKIP=''

[[ -e $FDISK_PATH ]] ||
{ echo "$FDISK_PATH is not a valid path to fdisk. Modify $0 with the correct path."; exit 1; }

#Remind user that they are not running fdisk directly
echo "Running fdisk wrapper script"

#If this script was run with any arguments other than "-l", pass the arguments
#to real fdisk
if [[ $# -ne 1 ]] || [[ $1 != "-l" ]]
then
	$FDISK_PATH $@
else
	which lsblk &>/dev/null ||
	{ echo "WARNING: lsblk is required, but was not detected. Running regular fdisk"; $FDISK_PATH -l; exit 1; }

	#Remind user that we are ignoring some disks
	echo -n "Ignoring disks: "
	echo $DEVICES_TO_SKIP | sed 's/ /, /g'

	#Run fdisk -l on all devices that are not on the ignore list
	IFS=$'\n'
	for DEVICE in $(lsblk -o KNAME,TYPE | grep 'disk$\|loop$\|dmraid$' | sort -u)
	do
		DEVICE="/dev/$DEVICE"
		DEVICE=$(echo $DEVICE | cut -d ' ' -f 1)
		SKIP=false

		IFS=' '
		for D in $DEVICES_TO_SKIP
		do
			if [[ $D == $DEVICE ]]
			then
				SKIP=true
				break
			fi
		done

		if ! $SKIP
		then
			$FDISK_PATH -l $DEVICE
		fi
	done
fi
